# Generated by Django 5.2.18 on 2026-10-09 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_last_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_id', models.UUIDField(unique=True)),
                ('kind', models.CharField(help_text='actuators, sensors ou config.', max_length=16)),
                ('action', models.CharField(max_length=32)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('sent', 'envoyée'), ('acked', 'confirmée'), ('failed', 'en échec'), ('timeout', 'sans réponse')], default='sent', max_length=8)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
                ('user', models.ForeignKey(blank=True, help_text='Vide pour une commande automatique (moteur ITK).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='command_device_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('source', models.CharField(help_text='Composant, ex. ClimateSensor.', max_length=64)),
                ('metric', models.CharField(help_text='Métrique, ex. temperature.', max_length=64)),
                ('value', models.FloatField(null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device')),
            ],
            options={
                'verbose_name': 'mesure',
                'verbose_name_plural': 'mesures',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['device', '-ts'], name='telemetry_device_ts_idx'), models.Index(fields=['device', 'metric', '-ts'], name='telemetry_metric_ts_idx')],
            },
        ),
    ]
