# Generated by Django 5.2.18 on 2026-10-09 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Identité matérielle dérivée de machine.unique_id() (ghb-xxxxxx).', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^ghb-[0-9a-f]{6}$', 'Identifiant matériel invalide (format attendu : ghb-xxxxxx, hexadécimal).')])),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('model', models.CharField(blank=True, help_text='Modèle matériel déclaré.', max_length=64)),
                ('fw_version', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', "en attente d'appairage"), ('provisioned', 'appairé'), ('disabled', 'désactivé')], default='pending', max_length=16)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bourgeon',
                'verbose_name_plural': 'Bourgeons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MqttCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(help_text='Ligne de mot de passe Mosquitto.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_credential', to='devices.device')),
            ],
            options={
                'verbose_name': 'identifiant MQTT',
                'verbose_name_plural': 'identifiants MQTT',
            },
        ),
        migrations.CreateModel(
            name='PairingClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('bootstrap_fingerprint', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_redeemed', to=settings.AUTH_USER_MODEL)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_claim', to='devices.device')),
            ],
            options={
                'verbose_name': "code d'appairage",
                'verbose_name_plural': "codes d'appairage",
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.site'),
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sensor', 'capteur'), ('actuator', 'actionneur')], max_length=8)),
                ('name', models.CharField(help_text='Nom du composant, ex. ClimateSensor.', max_length=64)),
                ('metrics', models.JSONField(blank=True, default=list, help_text='Métriques publiées par ce composant, ex. temperature, humidity.')),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='devices.device')),
            ],
            options={
                'verbose_name': 'capacité',
                'verbose_name_plural': 'capacités',
                'ordering': ['device', 'kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('device', 'kind', 'name'), name='unique_capability_per_device')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'propriétaire'), ('member', 'membre')], default='member', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='devices.device')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appartenance',
                'verbose_name_plural': 'appartenances',
                'ordering': ['device', 'user'],
                'constraints': [models.UniqueConstraint(fields=('device', 'user'), name='unique_membership'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('device',), name='unique_owner_per_device')],
            },
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_site_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'last_seen'], name='devices_dev_status_b6dd78_idx'),
        ),
    ]
