# Generated by Django 5.2.18 on 2026-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_state',
            field=models.JSONField(blank=True, default=dict, help_text='Dernier état connu : capteurs, actionneurs, statut et horodatage.'),
        ),
    ]
