# Generated by Django 5.2.18 on 2026-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'propriétaire'), ('member', 'membre'), ('viewer', 'lecteur (lecture seule)')], default='member', max_length=8),
        ),
    ]
