# Generated by Django 5.2.18 on 2026-10-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttcredential',
            name='bootstrap_revoked_at',
            field=models.DateTimeField(blank=True, help_text="Compte d'amorçage révoqué.", null=True),
        ),
        migrations.AddField(
            model_name='mqttcredential',
            name='installed_at',
            field=models.DateTimeField(blank=True, help_text='Premier message reçu avec ces identifiants : le boîtier les a bien reçus.', null=True),
        ),
    ]
