# Generated by Django 5.2.18 on 2026-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_mqttcredential_bootstrap_revoked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttcredential',
            name='installed_at',
            field=models.DateTimeField(blank=True, help_text='Prouvé par le premier message reçu avec ces identifiants.', null=True),
        ),
    ]
